# Generated by Django 3.1.1 on 2020-09-12 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_area_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpenterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField(max_length=200)),
                ('charges', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('timeopen', models.TimeField(default=datetime.time(9, 0))),
                ('timeclose', models.TimeField(default=datetime.time(20, 0))),
                ('is_avaliable', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carpenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
