# Generated by Django 3.1.1 on 2020-09-08 18:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlumberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('charges', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('timeopen', models.TimeField(default=datetime.time(9, 0))),
                ('timeclose', models.TimeField(default=datetime.time(20, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plumber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
