# Generated by Django 3.1.1 on 2020-09-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plumberprofile',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
