# Generated by Django 3.1.1 on 2020-09-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_area_city'),
        ('plumber', '0002_plumberprofile_is_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumberprofile',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.area'),
        ),
        migrations.AlterField(
            model_name='plumberprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city'),
        ),
    ]
